[tool.poetry]
name = "license-plate-recognition"
version = "0.1.0"
description = ""
authors = ["Dawid Badurek <dawid.badurek@besidethepark.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
